### PR TITLE
Change binom function to use much faster one 

### PR DESCRIPTION
**Pull request by thephez**
Updated function (found at https://stackoverflow.com/a/26561091) appears to return same results but cuts run time from multiple minutes to a few seconds. Only tested a few cases but they all matched the original.

### CODE REVIEW

**Comment by DarrenTa** [comment]
I tested this function and yes you are correct.  Thanks for the find!!

Now we can make a CSV with lots of data if we want.

**Comment by thephez** [comment]
You bet. I put a stripped down Python3 version that can be run online here - https://repl.it/@thephez/Quorum-Attack

**Comment by DarrenTa** [comment]
Note that y can be changed so the calculation can be done for an attacker with any number of nodes.  Also the quorum size and threshold could be changed as well.  I hope this is useful for you guys!!!!

**Comment by thephez** [comment]
I did not do anything with the quorum/threshold size, but this one will calculate a whole range of attackers - https://repl.it/@thephez/Quorum-Attack-Loop :wink:

**Comment by DarrenTa** [comment]
Very nice!

**Pull request merged**
